---
- name: Create the configuration file
  template:
    src: nginx.conf.j2
    dest: "{{ nginx__conf_file }}"
    owner: "{{ nginx__user }}"
    group: "{{ nginx__group }}"
    mode: "{{ nginx__file_mode }}"
  when:
    - nginx__conf_file is defined
    - nginx__conf_file != ''
  notify: Reload nginx service

- name: Remove managed vhost config file (if no vhosts are configured)
  file:
    dest: "{{ nginx__vhost_file }}"
    state: absent
  when: nginx__vhost_file is not defined or nginx__vhost_file != ''
  notify: Reload nginx service

- name: Add managed vhost config file (if any vhosts are configured)
  template:
    src: vhost.conf.j2
    dest: "{{ nginx__vhost_file }}"
    owner: "{{ nginx__user }}"
    group: "{{ nginx__group }}"
    mode: "{{ nginx__file_mode }}"
  when:
    - nginx__vhost_file is defined
    - nginx__vhost_file != ''
  notify: Reload nginx service

- block:
    - name: Create a sudoers file
      template:
        src: "{{ ansible_os_family }}.sudoers.d.j2"
        dest: "{{ nginx__sudoers_file }}"
        mode: "{{ nginx__file_mode }}"

    - name: Add the sudoers file to the sudo configuration
      lineinfile:
        dest: /etc/sudoers
        regexp: "^#include /etc/sudoers.d/{{ nginx__service_name }}$"
        line: "#include /etc/sudoers.d/{{ nginx__service_name }}"
  when:
    - nginx__group_has_sudo_rights
    - nginx__group != "root"
    - nginx__group != "wheel"
    - nginx__group != "sudo"
...
