---

- block:
    - name: Disable service and stop it
      systemd:
        name: "{{ nginx__service_name }}"
        enabled: "no"
        state: stopped
      failed_when: False
      notify: Systemd daemon reload

    - name: Delete the service systemd unit file if it exists
      file:
        path: "{{ nginx__system_service_file }}"
        state: absent
  when: service_manager == 'systemd'

- block:
    - name: Disable service and stop it
      service:
        name: "{{ nginx__service_name }}"
        enabled: "no"
        state: stopped
      failed_when: False

    - name: Delete the service startup file
      file:
        path: "{{ nginx__system_init_file }}"
        state: absent
  when: service_manager == 'service'

- name: Delete the service environment file
  file:
    path: "{{ nginx__system_environment_file }}"
    state: absent
...
