---
- name: Delete vhost config files
  file:
    dest: "{{ nginx__vhost_dir + '/' + item['name'] }}"
    state: absent
  when:
    - nginx__vhosts is defined
    - item['name'] is defined

- name: Delete the main configuration file
  file:
    path: "{{ nginx__conf_file }}"
    state: absent
  when: nginx__conf_file is defined
...
