---
- name: Delete service directories
  file:
     path: "{{ item }}"
     state: absent
  when: item is defined
  loop: "{{ nginx__directories }}"

- name: Uninstall main package(s)
  package:
     name: "{{ item }}"
     state: absent
  loop: "{{ nginx__packages[ansible_distribution][ansible_distribution_major_version|int]['packages'] }}"
...
