---
- name: Delete service directories
  file:
     path: "{{ item }}"
     state: absent
  when:
     - item is defined
     - item != ''
  with_items: "{{ nginx__directories }}"

- name: Deinstall main package
  package:
     name: "{{ item }}"
     state: absent
  with_items: "{{ nginx__packages[ansible_distribution][ansible_distribution_major_version|int]['packages'] }}"
...
