---
- name: Using SystemD manager to start service
  systemd:
    name: "{{ nginx__service_name }}"
    state: started
  register: nginx__service_started
  listen: Start nginx service
  when:
    - service_manager == 'systemd'
    - nginx__service_started is undefined or nginx__service_started.changed == False
    - nginx__service_restarted is undefined or nginx__service_restarted.changed == False
    - nginx__service_reloaded is undefined or nginx__service_reloaded.changed == False

- name: Using SystemD manager to stop service
  systemd:
    name: "{{ nginx__service_name }}"
    state: stopped
  register: nginx__service_stopped
  listen: Stop nginx service
  when:
    - service_manager == 'systemd'
    - nginx__service_stopped is undefined or nginx__service_stopped.changed == False

- name: Using SystemD manager to restart service
  systemd:
    name: "{{ nginx__service_name }}"
    state: restarted
  register: nginx__service_restarted
  listen: Restart nginx service
  when:
    - service_manager == 'systemd'
    - nginx__service_restarted is undefined or nginx__service_restarted.changed == False

- name: Using SystemD manager to reload service
  systemd:
    name: "{{ nginx__service_name }}"
    state: reloaded
  when:
    - service_manager == 'systemd'
    - nginx__service_started is undefined or nginx__service_started.changed == False
    - nginx__service_restarted is undefined or nginx__service_restarted.changed == False
  listen: Reload nginx service

- name: Run daemon-reload for SystemD manager
  systemd:
    name: "{{ nginx__service_name }}"
    daemon_reload: yes
  listen: Systemd daemon reload
  when: service_manager == 'systemd'
...
